---
version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: "developer"
      POSTGRES_DB: "openmusic"
      POSTGRES_PASSWORD: "supersecretpassword"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ../.data-open-music/postgresql:/var/lib/postgresql/data/pgdata

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
      - "25672:25672"
